# Generated by Django 2.2.6 on 2020-08-18 04:58

import boardapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateField(verbose_name='date_published')),
                ('hits', models.IntegerField(default=0)),
                ('upload_files', models.FileField(blank=True, null=True, upload_to=boardapp.models.get_file_path)),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
