# Generated by Django 2.2.6 on 2020-08-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoboard',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='파일 이름'),
        ),
    ]
