# Generated by Django 2.2.6 on 2019-11-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoboard',
            name='mail',
        ),
    ]
