# Generated by Django 2.2.6 on 2019-12-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_remove_djangoboard_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoboard',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='djangoboard',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
