# Generated by Django 3.1 on 2020-08-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_auto_20191219_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
