# Generated by Django 2.2.6 on 2020-07-29 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boardapp', '0003_auto_20191219_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoboard',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='djangoboard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='djangoboard',
            name='nick_name',
        ),
        migrations.AddField(
            model_name='djangoboard',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='djangoboard',
            name='content',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='djangoboard',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='djangoboard',
            name='subject',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
