# Generated by Django 3.1 on 2020-08-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_sub_board'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sub_board',
            new_name='SubBoard',
        ),
    ]
