# Generated by Django 2.2.6 on 2019-12-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
