# Generated by Django 2.2.6 on 2020-01-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoboard',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
