# Generated by Django 3.1 on 2020-08-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_auto_20200815_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataroomBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, max_length=50)),
                ('item', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('year', models.DateField()),
            ],
        ),
    ]
