# Generated by Django 2.2.6 on 2020-08-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_auto_20200729_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoboard',
            name='created_date',
            field=models.DateField(verbose_name='date_published'),
        ),
    ]
