# Generated by Django 3.1 on 2020-08-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0006_dataroomboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, max_length=50)),
                ('item', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('year', models.DateField()),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
