# Generated by Django 2.2.6 on 2019-10-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
