# Generated by Django 3.0.8 on 2020-08-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=10, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_ID',
            field=models.IntegerField(blank=True, null=True, verbose_name='학번'),
        ),
    ]
